global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: "tf-serving-monitor"
 
 
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s 
    metrics_path: /monitoring/prometheus/metrics 
    scheme: https
    static_configs:
      - targets: ['vigilant-surprise-production.up.railway.app'] 
